### ISSUE TITLE
Graphical glitches after recent updates

### ISSUE THREAD

**Issue by mlnlbrt** [libretro/flycast#50]
Recent updates made libretro version of reicast better than ever before, but I have noticed they have also broken some stuff.

These issues are present in both reicast and reicast-oit cores and were not present in earlier versions of libretro-reicast.

Hardware: PC with nVidia GT 1030 and C2D cpu ~3.8 GHz
Software: custom build of Lakka with X11 enabled, Retroarch ~1.67, 384.90 nVidia drivers and reicast cores downloaded from buildbot yesterday

1. Ball in Virtua Tennis lost its colors
![virtua tennis usa -180614-224112](https://user-images.githubusercontent.com/11428910/41474376-1bcc51aa-70bc-11e8-81c4-380a01aa5ed6.png)

2. Sometimes the screen is cut from the bottom. Noticed in Rez and Virtua Tennis so far, height seems to be the same in both cases.
NOTE: The issue does not occur when Internal resolution is increased to 1280x960.
![rez europe -180615-165821](https://user-images.githubusercontent.com/11428910/41475213-70dbd6be-70be-11e8-9a56-c10520762f01.png)

![virtua tennis usa -180614-224053](https://user-images.githubusercontent.com/11428910/41475191-5c12dd22-70be-11e8-8536-a4be6a5d9501.png)

3. Soul Calibur intro 
![soul calibur usa - 4s -180614-224232](https://user-images.githubusercontent.com/11428910/41475329-ceae79a4-70be-11e8-97fe-1754586d0a61.png)
![soul calibur usa - 4s -180614-224326](https://user-images.githubusercontent.com/11428910/41475339-d6452e56-70be-11e8-9741-0d5bf6522f2b.png)

There are also some slowdowns in Rez which were not happening earlier. I thought my emulation rig is not that bad but maybe not in this case. :)

Thanks!

**Comment by inactive123** [comment]
The Soul Calibur intro bug and the Virtua Tennis bug are things I have noticed myself yeah. I mentioned the Soul Calibur intro bug to @flyinghead, and I assume once he gets back from vacation he might look into it.

As for issue 2 (the screen sometimes being cutoff), does it happen when you go beyond 1280x960?

**Comment by mlnlbrt** [comment]
Tried 1280x960 and 1920x1440, no issues for both Rez and Virtua Tennis.
Seems that only 640x480 is affected.

**Comment by inactive123** [comment]
The ball issue in Virtua Tennis/Power Smash should be fixed now -

https://github.com/libretro/reicast-emulator/commit/988b53aae82a3144887199f1348ad0d1ad7a8dcc

**Comment by rcaridade145** [comment]
@twinaphex @flyinghead  There are references to bugs being introduced on a "optimization" of the texture cache on and threading on nulldc https://github.com/skmp/nulldc/commit/c96673e15ae40d2b55d7300962b6e3ceed6a5952#diff-da4106b97d1cefa1d4373cf66d1ec4cb  

https://github.com/skmp/nulldc/issues/463

https://code.google.com/archive/p/nulldc/source/default/commits

**Comment by inactive123** [comment]
@rcaridade145 Hi, here are the commits I made sometime ago which fixed some of the palette/sprite issues with Capcom Vs SNK 2 / Street Fighter III -

https://github.com/libretro/reicast-emulator/commit/ed7b9769359b647be158673b1c1a775c38a29eb1#diff-158be6f83a8533cb0f232fbb5fb8432a

https://github.com/libretro/reicast-emulator/commit/f2fd99c418df064c2477ecc1e8eaef953f7d9310#diff-158be6f83a8533cb0f232fbb5fb8432a

It could indeed be the case that more regressions were made during the nullDC period which were inherited by Reicast later on.

BTW, how goes the Shenmue 1/2 dynarec stuff?

**Comment by mlnlbrt** [comment]
Thanks, recent commits fixed ball in Virtua Tennis but I think they also introduced a regression: https://github.com/libretro/reicast-emulator/issues/66

**Comment by mlnlbrt** [comment]
Hi @twinaphex, something is still wrong with ball in Virtua Tennis.

With the latest nightly non-OIT build for linux x86_64 RTT is broken if RTT Buffer is disabled:
![virtua tennis usa -180629-174726](https://user-images.githubusercontent.com/11428910/42103536-ab7a8b10-7bc9-11e8-8c50-e1a6769b7f5d.png)

earlier it worked fine without RTT Buffer. If I enable RTT Buffer then RTT works, but something is wrong with ball again:
![virtua tennis usa -180629-174957](https://user-images.githubusercontent.com/11428910/42103603-dca0297a-7bc9-11e8-9b9f-fa537277645c.png)

**Comment by flyinghead** [comment]
It's broken in my fork as well. I'm looking at it.

**Comment by flyinghead** [comment]
@twinaphex I just pushed https://github.com/flyinghead/reicast-emulator/commit/7ecd38461209f303cdc866aeeb00be882365dc5d that should take care of this problem.
My earlier fix for Bomberman broke render to texture.

**Comment by inactive123** [comment]
Alright, let me go ahead and push that.

**Comment by inactive123** [comment]
Backported - https://github.com/libretro/reicast-emulator/commit/ee99f81c96a924e5e5179ffff36d9945bc39cc76

**Comment by inactive123** [comment]
@mlnlbrt Can this be closed or are there still remaining issues here?

**Comment by mlnlbrt** [comment]
@twinaphex I think Soulcalibur intro is still broken. I will close this one and create a separate issue for SC to keep things organized.
