### ISSUE TITLE
Screen Orientation upside down in shooters

### ISSUE THREAD

**Issue by Cavermendes** [libretro/flycast#566]
I'm trying to get shooters work but can't seem to get the right orientation. I switched the orientation in service mode in the system assignments menu since the game wouldn't boot otherwise. After the game boots vertically I then switched the orientation again but this time in the options menu for Flycast in Retroarch. For some reason this makes it so that the game is upside down instead of right side up. Are these games just supposed to be played vertically? Is there no way to flip the screen the other way instead? 
<img width="922" alt="Capture2" src="https://user-images.githubusercontent.com/52190891/60072951-18437380-96ed-11e9-94ae-9a08f5133d0f.PNG">
<img width="916" alt="Capture1" src="https://user-images.githubusercontent.com/52190891/60072957-1aa5cd80-96ed-11e9-9bbd-81ff1f536ef7.PNG">

**Comment by barbudreadmon** [comment]
Update core & retroarch, that bug was about "glcore" video driver & vertical games, it was fixed long ago.

**Comment by Cavermendes** [comment]
Thx for the quick reply, I thought I was running the latest version of both. I updated like 3 times in the past 2 days. What version should I be on?

**Comment by barbudreadmon** [comment]
> I thought I was running the latest version of both.

~~Your core is at the very least 1 month old, on your screenshot it's still showing as "reicast"...~~ Nvm, it seems the core is still showing itself as "Reicast" in RA UI...

> What version should I be on?

Any retroarch nightly from the past few weeks should do. Don't use stable or don't use glcore.

**Comment by Cavermendes** [comment]
I can't for the life of me update to the latest core. Is there something obvious I'm overlooking? I've tried to update through Retroarch and it's still in the same version. I tried using the Stellar updater but it says nothing needs to be updated. I even tried downloading Flycast directly from the buildbot nightly and replacing the .dll myself and still the same version. 
<img width="400" alt="Capture2" src="https://user-images.githubusercontent.com/52190891/60079173-60699280-96fb-11e9-8525-bccbce1c0364.PNG">

**Comment by barbudreadmon** [comment]
> I can't for the life of me update to the latest core.

Update **RetroArch**, as i said don't use stable or don't use glcore.

**Comment by Cavermendes** [comment]
I'm on the latest build. This is the latest nightly I downloaded. 

<img width="960" alt="Capture2" src="https://user-images.githubusercontent.com/52190891/60081002-f357fc00-96fe-11e9-8c37-a887b6ca1668.PNG">

**Comment by barbudreadmon** [comment]
Ok, re-opening then, i need you to test something : does it act the same on both "gl" & "glcore" video driver ?

**Comment by blisstik** [comment]
If you are using bin/dat. Try using mame zip.

________________________________

**Comment by barbudreadmon** [comment]
Oh yeah, it would make sense, bin/dat is unaware of native game rotation, so flycast's algorythm to auto-rotate will fail, don't use that format, it's full of issues so it's deprecated

**Comment by Cavermendes** [comment]
So I tried changing the video driver to "gl" and it still does the same thing. I also used the MAME zip file instead of bin/dat (which I was using for all my Sega Naomi games with no problem). They boot to a black screen like usual but then Retroarch crashes without going into the Naomi boot screen. I also don't think it's a BIOS issue since it works just fine whit the bin/dat format and all my BIOSes (is that a word?) are in the right place. Is there a specific MAME set that works with Flycast?

**Comment by Cavermendes** [comment]
<img width="723" alt="Capture2" src="https://user-images.githubusercontent.com/52190891/60128423-9ee56880-9760-11e9-9294-a4cfc9404667.PNG">
Here's my MAME rom set

**Comment by Cavermendes** [comment]
Looking back on it now it does seem like my Sega Naomi MAME zips are probably trash. There's no way Ikaruga takes up only 2KB of space. I'm going to look online for a better set then report back with my findings.

**Comment by Cavermendes** [comment]
So it turns out I was missing the Ikaruga .chd file (MAME is weird). After getting that I can finally say the game is the right side up. 
<img width="827" alt="Capture2" src="https://user-images.githubusercontent.com/52190891/60130853-14076c80-9766-11e9-8303-e813bb7476a5.PNG">

So should I change all my bin/dat collection to MAME .zip now or only do that for this problem? I have a shit ton of Sega Naomi titles and would like to keep them as is. Are there any other problems with using that format that you know of? The only other weird thing I noticed was that the Naomi boot sound was either not playing or was very low but the game sound was fine with the .chd file. Anyways, I believe this issue can now be closed. Thank you so much, both of you, for all your help and I hope you continue making this core as great as it can be.

**Comment by blisstik** [comment]
The only non-Mame rom you should keep is Gun Survivor 2 Biohazard Code Veronica as the Mame zip will load into black screen.

**Comment by Cavermendes** [comment]
Ok, good to know. Guess I'll have to update all my rom files. Any idea about not getting the Naomi boot sound? I checked and it's not low, it's just not there. I know it's a silly issue but I really liked it lol. Also, when exiting test mode it just gets stuck. Never had these problems with the other format, just the screen orientation one really.

**Comment by flyinghead** [comment]
Closing as resolved
