### ISSUE TITLE
Recent update broke Naomi games.

### ISSUE THREAD

**Issue by bslenul** [libretro/flycast#984]
Hey!

With a recent core update the Naomi games don't work properly anymore, in MVC2 and CVS2 for example it gives a "ERROR. JAMMA I/O BOARD NOT FOUND." a bit after the first loading, similar error with GGX, with Crazy Taxi no error but you can't insert coins it seems.

After bisecting, it looks like it started with e6dd855a05853fdf87142dc5745275c6f3ebfba6.

**Comment by barbudreadmon** [comment]
I reverted every recent changes yesterday, so this issue is fixed.

Some additional information about this : there are many differences between upstream and libretro, and while some might be worth backporting, a lot of those differences never were backported because they were irrelevant.

Anyway i plan on reducing this gap bit by bit whenever i have time.

**Comment by bslenul** [comment]
Yup, working again with aba25cd, thank you! ❤️ 

Do you want me to keep this open for upstream/libretro talks with other devs? Or can I close this?

**Comment by barbudreadmon** [comment]
let's close :)

**Comment by Smoker1** [comment]
Might need to Link the latest Working Builds of this, since it is still showing this Message. Someone on Reddit Posted that the Build 0.1 1249145 from around November 15 works.

**Comment by barbudreadmon** [comment]
> since it is still showing this Message

@Smoker1 that's because the buildbot is currently broken and providing old versions of the core.
